---
- name: Update package lists
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: Add Docker GPG key
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"

- name: Add Docker APT repository
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |-
      deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable

- name: Update package lists again
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: "{{ docker_package }}"
    state: present
  vars:
    docker_package: 
       - "docker-ce"
       - "docker-ce-cli"
       - "containerd.io"

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Reload Docker daemon (if changes made)
  systemd:
    name: docker
    daemon_reload: True

- name: Pull Docker image from Docker Hub
  docker_image:
    name: tomlui2010/pppcalculator
    tag: latest
    source: pull

- name: Run backend Docker container
  docker_container:
    name: pppcalculator_backend
    image: tomlui2010/backend-pppcalculator:latest
    state: started
    ports:
      - "5000:5000"
    env:
      SECRET_FILE: "{{SECRET_FILE}}"

- name: Run frontend Docker container
  docker_container:
    name: pppcalculator_frontend
    image: tomlui2010/frontend-pppcalculator:latest
    state: started
    ports:
      - "8000:3000"
